import Loading from "@/components/Loading/Loading";
import { StoreProvider } from "./StoreProvider";
import "jsvectormap/dist/jsvectormap.css";
import "flatpickr/dist/flatpickr.min.css";
import "@/css/satoshi.css";
import "@/css/style.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Loading>{children}</Loading>
        </body>
      </html>
    </StoreProvider>
  );
}
